### ISSUE TITLE
Shipkit 1.0

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#116]
The purpose of this ticket is to flesh out what else is needed to release 1.0.

Everything below is negotiable. Feel free to add things. Instead of removing, use ~~strike through~~.

- Mockito build on latest Shipkit
  - [x] - automated publication to Maven Central enabled
  - [x] - notable/detailed release notes tidy up - #157 
  - [x] - contributors fetching from @mstachniuk feature in (some work on @szczepiq's end)
  - [x] - publications prevention from @wwilk feature in
- API
  - [x] - Javadoc on all public types
  - [x] - All types intended to be public in 'public' package, internal types under 'internal' - https://github.com/mockito/mockito-release-tools/issues/178
  - [x] - Plugins rename
- Documentation
  - [x] - see #432
- Testing / dogfooding / bootstrapping
  - [ ] - ~~a new sample project that pushes to Maven Central (currently our sample project pushes to Bintray). The new sample project would be a "minimal" project, with least amount of configuration. It would also act as documentation.~~
  - [x] - shipkit dogfoods itself (release notes, versioning)
- Misc
  - [x] - bootstrap mechanism so that we can demonstrate how easy it is to setup CD. We could screencast it 
  - [ ] - ~~Avatar for shipkit-org user so that we look good [commits view](https://github.com/mockito/mockito/commits/release/2.x). Looking good is important because it adds credibility~~ :)

**Comment by szczepiq** [comment]
@wwilk, does Mockito build leverage the publication avoidance feature? It's one of the checkboxes on the list ;)

**Comment by TimvdLippe** [comment]
We are pretty far with this right?

**Comment by szczepiq** [comment]
>We are pretty far with this right?

We are! I've checked the boxes in the plan.

**Comment by TimvdLippe** [comment]
Hm, it only shows one checke box. Maybe something went wrong?

**Comment by epeee** [comment]
closing this one since we already released 1.0.
