### ISSUE TITLE
Some contributor links are missing in Mockito release notes

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#147]
Some contributor links are missing in recent [Mockito release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md). Copy paste from notes, Christian Schwarz and Serge Bishyr link is missing:

**2.8.29** - [7 commits](https://github.com/mockito/mockito/compare/v2.8.28...v2.8.29) by [Szczepan Faber](http://github.com/szczepiq) (5), Christian Schwarz (1), Serge Bishyr (1) - *2017-05-15* - published to [maven/mockito-development](https://bintray.com/mockito/maven/mockito-development)

Most likely, some of my recent refactorings broke it :)

**Comment by szczepiq** [comment]
I was thinking about options to solve the contributors problem. I think it's very useful to get it right because it will pave the way how we will solve similar changes when we grow the plugins. Here are our options (there could be even more, but I think the list is pretty much complete). The options are written using Gradle jargon and with my own mental shortcuts - pardon me if this is hard to grok.

### Options

1. **File based**: Task that needs contributors has an optional File input property, and depends on fetch all contributors task. During execution they would deserialize all contributors unless the file is not provided. This is the approach we did before we introduced "configureContributors" task.

* simple, intuitive
* duplicated deserialization efforts if there are many tasks that need contributors, pushes us to make contributors serialization/deserialization utilities public otherwise the tasks are not easily reusable outside of our plugins (or we would have to make the JSON format public.

2. **Task based**: Task that needs contributors depends on “configureContributors” task and gets configured from 'team.contributors'. The approach is relatively simple, single deserialization per build. This is more less the approach we have right now (with bugs :).

* 2a) use “doFirst" to configure contributors from releasing.team.contributors (doFirst to make sure we configure the contributors after ‘configureContributors’ have executed). Using doFirst to configure self makes the task hard to reconfigure by the user, it is also counter intuitive and easy to forget.
* 2b) “configureContributors” task can explicitly configure contributors on the specific tasks, instead of updating releasing.team.contributors. Makes configureContributors coupled with every task that needs contributors or we would have to expose a new interface called RequiresContributors (things are getting complicated)

3. **Shared state**: Task that needs contributors shares state with other tasks that need or provide contributors. This is the approach suggested by @mstachniuk in the pull request. Very simple approach but tasks are harder to reuse, cannot tweak one task without changing other task.

* 3a) we can share an instance of a list (like in #150 by @mstachniuk)
* 3b) we can share an instance of releasing.team

### Recommendation

I suggest we go for option 1 as it was originally implemented by @mstachniuk. This approach is relatively simple and it is consistent with how we do things elsewhere - for the release notes generation serialization/deserialization. We can add some tweaks to the code to avoid duplicated deserialization of the same file during the same build.

**Comment by mstachniuk** [comment]
Close by https://github.com/mockito/shipkit/pull/167
