### ISSUE TITLE
Bootstrap project to demonstrate and learn Shipkit

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#148]
## Idea

We need an dead simple way of demonstrating and experimenting with with Shipkit. Use cases:
 - adoption, getting more users - the easier it is to try out Shipkit the better chance we attract users
 - demos, conferences - if we can set up a new project and configure continuous delivery pipeline in short time (<1 minute) it would should be pretty awe-inspiring :)

## Use scenarios

- I have a java project with no release automation yet.
  - Apply "org.shipkit.java" plugin to my root project's "build.gradle" file.
  - ```./gradlew initShipkit``` and have decent prompts telling me what is happening.
  - Commit code.
  - ```./gradlew performRelease``` binaries are published to Bintray (using default bintray-bootstrap-bot account) and code is pushed to GitHub (using 'git push' without write token, because write token is not yet configured at this point).
- I performed 1st release of my java project from my local. How do I setup continuous delivery?
  - enable Travis CI
  - create pull request and merge
  - observe failure and follow prompts - generate GitHub write token and configure GH_WRITE_TOKEN in Travis CI
  - restart job in Travis CI
- I want to experiment with Shipkit
  - Fork and clone ["shipkit-bootstrap"](https://github.com/mockito/shipkit-bootstrap) and follow it's README.md

**Comment by szczepiq** [comment]
I updated heavily use scenarios, take a look. Most importantly, I'm thinking of relaxing the github write token requirement for the release: if the token is not configured / exported in env variable, we will just perform git push from local. This will really streamline demos and make the bootstrapping scenarios simple. Plus, some users who are happy to be releasing from local can just keep it this way.

**Comment by wwilk** [comment]
I think this one is already done, so I'm closing the issue
