### ISSUE TITLE
Bump tools in Mockito project - avoid releasing versions if nothing changed

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#156]
Let's bump the version of tools in Mockito project so that we can take advantage of avoiding publications from @wwilk! Mockito just released new version ([build](https://travis-ci.org/mockito/mockito/jobs/233634562), [release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md)) but publications haven't really changed ;) If someone submits PR to Mockito project, I would love to merge it!

**Comment by wwilk** [comment]
Sure! I will do that, probably tomorrow :)

**Comment by szczepiq** [comment]
Can this ticket be closed? Does Mockito leverage the release avoidance? I would love to include it as one of the features of Shipkit 1.0 :)

**Comment by wwilk** [comment]
Not yet, I waited for pull request with changes in publicationsComparator logging to be merged. Now it can be used, I will get back to it soon.
