### ISSUE TITLE
Make assertReleaseNeeded task more informative

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#209]
### Problem

Currently, assertReleaseNeeded task produces following, not very informative message to the end user ([Travis CI log](https://travis-ci.org/mockito/mockito/jobs/239468959#L513)):

```
> Release is needed: false
 - skip by env variable: false
 - skip by commit message: false
 - is pull request build: false
 - is releasable branch: false
 - anything changed in publications since the previous release: true
```

### Use cases

We have following use cases:

1. Quickly understand why release is not needed, when reasons are obvious (like we are building a pull request)
2. Fully understand why release is not needed, when reasons are not obvious (possible bug, edge cases)
3. Understand what are the criteria for making the release. The criteria live in code so it's best if the documentation about them is also in code, in form of clean log messages.

The purpose of this ticket is to satisfy all above use cases. I think we do it currently, but the information is not human readable, so effectively we are not satisfying the use cases well.

### Suggested fix

Let's write something more human readable, that any could understand on the spot. When working on this feature, please ask somebody for feedback, ideally from outside our team :)

Example:

```
Release is not needed at this time so the build will fail preventing the release.
Release is considered _not_ needed when:
 - 'SKIP_RELEASE' environment variable is present (currently: false)
 - commit message contains "[ci skip-release]" (currently: false)
 - we are building a "pull request" (currently: false)
Release is needed when all above is false and: 
 - we are building on a branch that matches regex 'xxx' (currently: false)
 - there are changes in the binaries when compared to previous version (currently: true)
```

Feel free to suggest a different text, so long we make progress on making it super clean and descriptive.

### Implementation

- see the code of [ReleaseNeededTask](https://github.com/mockito/mockito-release-tools/blob/3f90104d0740604cfbcd318896fe6f2908b94747/src/main/groovy/org/shipkit/gradle/ReleaseNeededTask.java#L131)
- please ensure very comprehensive test coverage. This feature is very sensitive, conditional complexity here is high, we had bugs in this code before.

**Comment by NagRock** [comment]
When release is not needed, we want to see all possible reasons with `false` status or maybe only real reasons? For example: `Release is not needed at this time, the build will fail preventing the release because 'SKIP_RELEASE' environment variable is set`?

**Comment by szczepiq** [comment]
@NagRock, good question! Thank you for signing up for this improvement!

I'm about to merge a nice PR from @wwilk: #199, take a look in the description of that PR the current output of release needed task (it is related). The goal is to make it clean and easy to read. It will not only help with debugging but also build credibility of Shipkit - people evaluate the quality of tools by the quality of output they produce.

>When release is not needed, we want to see all possible reasons with false status or maybe only real reason? For example: Release is not needed at this time, the build will fail preventing the release because 'SKIP_RELEASE' environment variable is set?

We have following use cases:
 1. quickly understand why release is not needed, when reasons are obvious (like we are building a pull request)
 2. fully understand why release is not needed, when reasons are not obvious (possible bug, edge cases)
 3. understand what are the criteria for making the release. The criteria live in code so it's best if the documentation about them is also in code, in form of clean log messages.

The purpose of this ticket is to satisfy all above use cases. I think we do it currently, but the information is not human readable.

Coming back to your question, I think we need both. It would be cool to have one-liner summary at the top like: ```"Release is not needed at this time because 'SKIP_RELEASE' environment variable is present. Stopping the build now."```, followed by more comprehensive list of criterions to satisfy use cases 2) and 3).

Users love clean logs and clean error messages :) Thanks again for working on this!

**Comment by NagRock** [comment]
Thanks, it's clear now.

**Comment by szczepiq** [comment]
Hey @NagRock, friendly ping :)

**Comment by NagRock** [comment]
I'm little busy last days but will work on this.

**Comment by szczepiq** [comment]
Friendly ping :)
