### ISSUE TITLE
Enable consistent code style validation

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#22]
To keep the code clean and also to maximize the value of the code review, let's make the tools validate consistent code style for us.

- [x] enable Gradle Checkstyle plugin and make the build fail on coding style issues
- [x] enable Gradle Codenarc plugin, fail on issues
- [x] clean up the codebase and submit PR
- [ ] ensure it is enabled for test code (see https://github.com/mockito/shipkit/issues/22#issuecomment-333379214)

**Comment by szczepiq** [comment]
@epeee, can we close this ticket after your PR was merged (see the checklist :)?

Thank you for contribution!!!

**Comment by epeee** [comment]
@szczepiq yes, I think so.

You're welcome!

**Comment by szczepiq** [comment]
Closing with pleasure :) BTW. do you have a twitter handle?

**Comment by epeee** [comment]
@szczepiq no twitter handle (yet).

**Comment by szczepiq** [comment]
Hmmm, can we check if this is enabled for test code? I just stumbled upon PluginSpecification class that had incorrect whitespace and Checkstyle did not detect it.

Let's keep the house clean! :)

**Comment by epeee** [comment]
I will have look at this one.

**Comment by szczepiq** [comment]
Thank you!
