### ISSUE TITLE
Start shipping Javadoc

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#233]
### Problem

Currently, we rely on external https://javadoc.io service to host viewable Javadoc. When we publish the jars with javadocs to Maven Central, the javadoc is automatically downloaded, unzipped and hosted at javadoc.io. This works well for projects that ship to Central. Projects that don't ship to Central (some project ship only to https://bintray.com) don't get this benefit. Best example is Shipkit project itself - currently we don't host unzipped Javadocs that are easy to view online.

### Design spec

See PR #697

**Comment by szczepiq** [comment]
@mstachniuk, do you want to scope this ticket a bit more? I can help if needed :)

**Comment by mstachniuk** [comment]
I will do after a long weekend.

**Comment by mockitoguy** [comment]
@mstachniuk, how's life? Will you be able to take a stab at this feature? Cheers!

**Comment by mockitoguy** [comment]
I worked on designing the plugin today and added a pseudo code design to the description. Hope it helps!

**Comment by mstachniuk** [comment]
@mockitoguy Sure, it will help me. Thank you!

**Comment by mockitoguy** [comment]
@mstachniuk, the design spec is ready #697 :)

**Comment by mstachniuk** [comment]
It's in progress...
