### ISSUE TITLE
Create open "shipkit" google mailing list

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#234]
Due to team membership, this needs to be worked on by one of the core team members

### Problem

The mailing list is sometimes useful:
 - when contacting Travis CI support, I can cc the list
 - when I get some important email (like the fact that conference talk was accepted) I can just forward it to the mailing address
 - some members of the community might be oldschool and prefer emails
 - it adds visibility to what is happening in the project

We can also configure Slack to get emails automatically posted to Slack

Let's:
 - [x] retire mockito-release-tools list
 - [x] create open shipkit list: https://groups.google.com/forum/#!forum/shipkit
 - [x] update README.md how we use the mailing list (bugs, feature requests, questions should be submitted as GitHub issues)
 - [x] integrate slack

**Comment by mstachniuk** [comment]
Everything from the list is done.
