### ISSUE TITLE
Make Shipkit the best option for releasing Open Source Gradle plugins

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#255]
## Automated releases for Gradle plugin authors

Let's make Shipkit the best option for releasing Open Source Gradle plugins. Let's help Gradle community by providing means to fully automate release process: automated release notes, publication, documentation, versioning, tagging.

## Design

- [ ] Plugin "org.shipkit.gradle-plugin" produces release notes
- [ ] Documentation: [wiki page placeholder](https://github.com/mockito/shipkit/wiki/Shipkit-Gradle-Plugin-Reference#shipping-gradle-plugin)

## First steps

- See the starting point design at: https://github.com/mockito/shipkit/pull/283
- This issue needs reasonable understanding of the codebase. Let us know if you want to get started on this!

**Comment by mockitoguy** [comment]
Closing. I created a milestone instead: https://github.com/mockito/shipkit/milestone/2

**Comment by TimvdLippe** [comment]
Note that the README still references this issue. Is that intended?
