### ISSUE TITLE
When release fails the Travis Build should fail

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#257]
### Problem

When release logic breaks, we don't immediately find out (the build is green). Release invocation is a part of "after_success" step of CI workflow. Failures of "after_success" Travis CI steps do not mark the build as failed.

### Proposed solution

Current recommended configuration of Travis CI:

```
script:
  - ./gradlew build
after_success:
  - ./gradlew assertReleaseNeeded && ./gradlew ciReleasePrepare && ./gradlew performRelease -Pshipkit.dryRun=false
```

Desired configuration:

```
script:
  - ./gradlew build && ./gradlew ciPerformRelease
```

### Considerations

1. The reason we use "after_success" at the moment is because of "assertReleaseNeeded" task. It is a very easy way for us to implement a gate check before other tasks are executed. If "assertReleaseNeeded" other invocations of Gradle that follow bash' "&&" are not invoked.
2. It is hard to implement this use case because of Gradle task model work. I have a feeling that we should keep things simple and wait for Travis CI stages to get implemented, then revisit. I'm still thinking how to implement it, suggestions welcome.
3. The need for "-Pshipkit.dryRun=false" will be eliminated when we finish #236 (let's do it guys! who's up for it?)

**Comment by szczepiq** [comment]
Assigned to myself. I have an idea how to solve it.

**Comment by szpak** [comment]
+1 for the change - the build result is currently very unintuitive.

As the release is not mandatory for every build (can be skipped - or looking on a number of Mockito builds IMHO it could be triggered on demand, when needed, not enabled by default (but it is an another discussion :) )), it could just finish build successfully with visible information that release was not triggered (and why). People (authors or users) should notice that there are no new builds (especially having notifications about them enabled).

Waiting for Travis pipelines is somehow a vendor lock-in. Not all CI vendors might provide that feature and it would be probably good to implement it inside ShipKit.

**Comment by szczepiq** [comment]
Good feedback, thank you!

This is implemented now. This is recommended way of configuring Travis CI now:

```
script:
  - ./gradlew build && ./gradlew ciPerformRelease
```
