### ISSUE TITLE
Why use old gradle 2.14 wrapper?

### ISSUE THREAD

**Issue by tonit** [mockito/shipkit#263]
Is there a reason you have the gradle wrapper set to 2.14? I mean.. you still can make the plugin produced work against an older (more widely used) API but still use gradle 4 or whatever is the "hot stuff"? Or is this a false assumption?

**Comment by szczepiq** [comment]
Good question! The safest way to guarantee compatibility is to keep the wrapper at last 2.* version ;)

**Comment by szczepiq** [comment]
I will close it for now. At some point we will upgrade Gradle. It is not a high proprity at the moment (giving better compatibility is higher priority).

Thanks for reporting!
