### ISSUE TITLE
Task assertReleaseNeeded fails because of wrong discovered branch name on Travis CI

### ISSUE THREAD

**Issue by mstachniuk** [mockito/shipkit#264]
In task `assertReleaseNeeded` we read current branch name using this git command:

```
git rev-parse --abbrev-ref HEAD
```

It's a valid command util we are not in detached head (then above command return `HEAD`)! Unfortunately Travis-CI does `git checkout -qf sha1` after clone:
https://travis-ci.org/mockito/shipkit-example/builds/247233789#L146

and branch name is other as expected in `assertReleaseNeeded`:
https://travis-ci.org/mockito/shipkit-example/builds/247233789#L408

The newest version of shipkit-example in bintray is 0.15.2 instead of 0.16.3 (13 revisions are missing).

**Comment by szczepiq** [comment]
Fantastic bug report. Thank you!!!
