### ISSUE TITLE
Always clean up local git settings after running task with change git user and email

### ISSUE THREAD

**Issue by mstachniuk** [mockito/shipkit#271]
We have 2 tasks with change a local project git settings: `setGitUserName` and `setGitUserEmail`. This tasks should be undo at the end of the build to avoid commit by the user as `shipkit.gitHub.writeAuthUser`. We can use `finalizedBy` for that:
https://docs.gradle.org/2.14/dsl/org.gradle.api.Task.html#org.gradle.api.Task:finalizedBy

Just to not forget, probably all tasks with can run after `setGitUserName` and `setGitUserEmail` should be finalizedBy the undo task:
https://discuss.gradle.org/t/execute-finalizedby-even-if-task-fails/5683

Commands to execute:
```
git config --local --unset user.name
git config --local --unset user.email
```

It should be also possible to execute undo task manually form command line.

**Comment by szczepiq** [comment]
In what scenarios cleanup the git user is useful? On CI machine, the checkout directory is removed and not reused. On local, we don't run ciReleasePrepare so there is no need to revert user setting.

**Comment by mstachniuk** [comment]
It's useful when you call `ciReleasePrepare` task locally. It happens to me that later I commited using shipkit.org user.

**Comment by wwilk** [comment]
It seems that this is only useful for rare scenarios where you would test **ciReleasePrepare** locally. I don't think it's worth messing up the task space with tasks that have no significant use for the customers. Maybe a bash script for developers?

**Comment by mockitoguy** [comment]
Let's close without fixing. We can always reopen.
