### ISSUE TITLE
Include released version number in release commit

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#276]
## Problem

The released version number is not included in the release commit. Sample release commit messages:
> version bumped [ci skip]

> version bumped + release notes updated

For people getting through the commit list it is hard to get know which commit is included (or not) in a particular version (or when that version was released). That in turn can be useful to diagnose if the project using a given ShipKit version is affected by some bad commit (or contains some desired commit).

## Proposed solution

A version number could be put into the release commit message. E.g.
> Release version x.x.x

(could be configurable in the following iteration)

The extra information about version bumping and/or release notes generation are IMHO less important and could be put in the second commit line (aka body) which can be inspected on demand by interested parties.

## Extra information

I'm missing that feature in Mockito and therefore I could implement it in ShipKit if desired by The Development Team.

**Comment by szczepiq** [comment]
This is a great idea! Sorry we have not responded earlier - flying to Poland and prepping for Confitura was pretty absorbing :)

How about we change the commit message to (I don't know how easy is to get hold of previous version but it should be):

"1.0.1 release (previous 1.0.0) + release notes update"

Absolutely useful feature. Thank you for reporting and looking forward to pull request!

**Comment by szpak** [comment]
I tend to use Git tags based versioning instead of file based and probably because of that I do not get everything in your versioning model. For example, I haven't though about previous version as something especially important. Probably it can simplify the versioning implementation, but I'm not sure what would it bring to put `previous 1.0.0` in the commit message. In the Git history there should be previous entries with earlier version releases. Wouldn't be enough to have just the current version in the commit message?

**Comment by szczepiq** [comment]
>Wouldn't be enough to have just the current version in the commit message?

It would certainly be an improvement so go ahead either way.

Having previous in commit message is a small thing, and does not hurt to add (at the point of constructing the message, we have access to VersionInfo object that contains previous version). In Mockito we used to include the previous version in the commit message and it was ok. I don't claim it has huge value, though. Your concerns are valid!

Thank you for looking into this!

**Comment by szpak** [comment]
Closing as available in [0.8.119](https://github.com/mockito/shipkit/commit/88544ecc3f2e101b2545e4c01f278c22f8350251).

> 0.8.119 release (previous 0.8.118) + release notes updated [ci skip]
