### ISSUE TITLE
Failover for publicationsComparatorTask

### ISSUE THREAD

**Issue by wwilk** [mockito/shipkit#280]
## Problem
PublicationsComparatorTask downloads artifacts of previous version, sometimes they are not available because bintrayUpload task failed (silently or not). Since gitPush task runs before bintrayUpload, version could be bumped anyway. When download fails -> assertReleaseNeeded fails too. The only solution in this case is manual change of previousVersion to the last one that was actually released.

## Proposed solution
In case there is a fail during download we should not fail assertReleaseNeeded. Additionally we can try to automatically choose the last version actually released on Bintray. It has to be checked if Bintray latest URL can be used, or alternatively we can try to download artifact for the few latest tags, but in the latter case we have to remember about limiting these retries.

**Comment by szczepiq** [comment]
Great idea. At the very least we should not fail assertReleaseNeeded!

**Comment by szczepiq** [comment]
I'm working a lot in publications comparison. This is very nice code and works well! I'm updating the Gradle part of the API and should be able to fix this problem soon.

**Comment by szczepiq** [comment]
This is done!
