### ISSUE TITLE
Automatically validate plugin property files

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#284]
### Problem

Gradle plugins String identifiers are configured using ```META-INF/gradle-plugins/*.properties``` files. This is problematic because:
 - we need to manually ensure that all our plugins have corresponding *.properties file
 - when we rename the plugin class we forget to rename the *.properties file

### Suggested resolution

Add task that validates that:
 - all plugins have corresponding *.properties file
 - the name of *.properties file is consistent with the class name. E.g. "BintrayReleasePlugin.java" -> "org.shipkit.bintray-release" plugin identifier.

### Getting started

- see PluginDiscoveryPlugin which discovers plugins based in *.properties files
- create a new plugin, for example PluginValidationPlugin (cool name, huh? :) that adds new task. PluginDiscoveryPlugin would be automatically applied by GradlePluginReleasingPlugin
- to test, see README.md how to install locally, configure shipkit to use latest version of self, run the new task

**Comment by szczepiq** [comment]
@epeee, you might be interested looking into this one. It is related to plugin autodiscovery plugin that works really well and is one of the cool features of Shipkit support for Gradle plugin authors.

**Comment by epeee** [comment]
@szczepiq yes, I will work on this one.

**Comment by szczepiq** [comment]
Let's close this ticket and open a separate one for improvements! So far the plugin and the task looks promising, we need to figure out how to deal with false positives.
