### ISSUE TITLE
Autodiscover name of github repository

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#285]
### Problem

Shipkit needs to configure all defaults that can be automatically inferred. This way, the user only has to specify minimum amount of configuration. Currently we explicitly specify ```shipkit.gitHub.repository``` setting in ```shipkit.gradle``` file (see [Mockito's "shipkit.gradle"](https://github.com/mockito/mockito/blob/release/2.x/gradle/shipkit.gradle#L2) file). It would be great to infer the name of the repository automatically.

### Design

- We already have logic that identifies the current git repository, see InitShipkitFileTask
- Implementing this functionality is not trivial because getting repository information requires us to call external git command. We don't want to call git command during Gradle's configuration time. So we need to do it during task execution.
- One of the options to deal with above is to create task 'identifyGitRepository' and use it in similar way we currently use 'identifyGitBranch' task. However, it's going to be a bit of work because we use "repository" all over the place in Shipkit.
- Touch base if you want to work on this and you have more questions!!!

**Comment by anicos** [comment]
@szczepiq can you assign me?

**Comment by wwilk** [comment]
It seems that I can't assign someone not from the team, but it's ok, you can work on that, I think a comment is enough information for others.

**Comment by szczepiq** [comment]
@anicos, are you still interested in working on this? Cheers!

**Comment by anicos** [comment]
Hi. @szczepiq right now I can't take this task. If anyone wants to take it's free:)

**Comment by szczepiq** [comment]
We need to implement this feature because it is blocking #363

I'm on it :)

**Comment by szczepiq** [comment]
I identified where we need to fix it. In GitPlugin we use the repository name from shipkit configuration (org/shipkit/internal/gradle/git/GitPlugin.java:80), instead of inferring it from git origin.

**Comment by szczepiq** [comment]
We cannot really implement this. Let's close.

There are use cases where it is very useful to have have the repo name checked in to the source control. For example, it makes creation of pull requests from forks easier. Also, it makes some useful tasks like preview release notes useful when origin repository is forked.
