### ISSUE TITLE
Broken release notes generation in Shipkit itself?

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#298]
There is just one - the latest [entry](https://github.com/mockito/shipkit/blob/88544ecc3f2e101b2545e4c01f278c22f8350251/docs/release-notes.md):

```
0.8.119 (2017-07-07) - 2 commits by Szczepan Faber - published to Bintray
    Simplified shipping of shipkit, added release notes (#297)
```

**Comment by szczepiq** [comment]
It's because previous release in version.properties file was set to 0.8.118. For this use case, we should probably manually generate the release notes.

**Comment by szczepiq** [comment]
Thanks for reporting! Do you have suggestions on how to handle this better? This is a corner case - an introduction of the plugin that is still in-progress.

**Comment by szczepiq** [comment]
I suspect we can close it.
