### ISSUE TITLE
Release notes mechanism misses commits done before the previous release

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#299]
### Problem description

Some older commits are not mentioned in release notes.

### Steps to reproduce

1. Do nice commit
2. Create a pull request
3. Release version X
4. Merge PR
5. Release another version X2

### Expected behavior

"Nice commit" is mentioned in the release notes for X2.

### Actual behavior

"Nice commit" is not mentioned in the release notes for X (it was not already merged). It's also not mentioned in X2 - its commit date is before the release of X.

Sample [release](https://github.com/mockito/shipkit/commit/88544ecc3f2e101b2545e4c01f278c22f8350251) with commits from #294 missed.

### Simple analysis and proposed solution

The release notes mechanism seems to take into account the commit dates. Instead date order a topological order should be used. I haven't checked, though, if Git tool used in release notes supports that.

**Comment by szczepiq** [comment]
I suspect it's because we didn't search for commits prior to 0.8.118 release. We will double check this. Thanks for reporting.

**Comment by mockitoguy** [comment]
This should work. If not, we will reopen. Thank you for reporting!
