### ISSUE TITLE
PowerMock CR: call additional task before bumping version.

### ISSUE THREAD

**Issue by thekingnothing** [mockito/shipkit#334]
PowerMock is aimed on legacy project, so there are [developers](https://github.com/powermock/powermock/issues/814) who use PowerMock with Ant and have to download artefacts manually. 
As result PowerMock have to create a distributions packages, beside main artifacts:
- [zip/tar files](https://dl.bintray.com/powermock/generic/distributions/) with jars and sources 
- [fat full jars](https://dl.bintray.com/powermock/generic/org/powermock/powermock-mockito2/1.7.0/) with source

These artifacts are uploaded to separate Bintray repository which is not synced with Maven Central. 
I think it should be additional configuration/task/hook that will be called during release after checking that release is required but before changing version and pushing to Git.

**Comment by thekingnothing** [comment]
Another option is that  Shipkit can creates distributions packages and upload them to configurable artifact repository.

**Comment by szczepiq** [comment]
>These artifacts are uploaded to separate Bintray repository which is not synced with Maven Central.

How they are uploaded to Bintray? Using a Bintray Gradle plugin?

@wwilk, we could experiment with applying "org.shipkit.bintray" plugin and and then configuring the package to publish extra artifacts to Bintray repo.

**Comment by mockitoguy** [comment]
This ticket can be closed. Please reopen if needed!
