### ISSUE TITLE
Avoid unnecessary hits to GitHub REST API during non-release build

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#345]
### Problem

When performing a regular build, e.g. without the intention to release the artifacts, we should avoid hitting GitHub unnecessarily. Currently it happens because we automatically pull in contributors for pom.xml file.

### Steps to reproduce

 - clone example project
 - ```rm -fr build``` (in case you already have one)
 - ```./gradlew build``` - notice that we're hitting GitHub endpoints

### Implementation approaches

A) **Caching**: cache the results locally in a directory outside of the project, so that we can reuse them and avoid hitting GitHub. Complicated and hard to debug. Some GitHub calls we cannot cache because they change daily.
B) **Avoidance**: hit GitHub only when the intention is to publish artifacts, during normal build:
    - “./gradlew build” does not hit GitHub (does not require network)
    - “./gradlew performRelease” does hit GitHub (require network)

### Avoidance approach implementation options

1. Release needed produces a file that other tasks can inspect to see if the release is needed. This file is read by fetchContributors, if release is not needed, we fetchContributors does not hit GitHub. This option adds complexity.
2. We make a change: “bintrayUpload" depends on “fetchContributors” (in JavaBintrayPlugin), POM_TASK must run after “fetchContributors” (in PomContributorsPlugin). Pom task is already safe and does not fail with the contributors file is missing. This option is simple enough.
    - Going down this path means that we should implement #437 soon. Otherwise non core developers that exclude bintrayUpload task during Shipkit testing will not be testing fetchContributors.

**Comment by mockitoguy** [comment]
Also filled in Mockito project: https://github.com/mockito/mockito/issues/1248

@epeee, do you want to take a stab at it? :) It would be great!

**Comment by epeee** [comment]
yes, I will work on this one soon.

**Comment by epeee** [comment]
It looks like the chicken-and-egg problem no longer exists since ComparePublicationsPlugin is no longer using the pom. Therefore we could hit github only if a release is needed now, isn't it?

Removing the following lines would solve the problem mentioned in this issue.
https://github.com/mockito/shipkit/blob/0199b94152ff99ecbf65794f6ea666e21ddfc4ab/subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/java/JavaPublishPlugin.java#L65-L66
@mockitoguy do you know which problem(s) the comment above is referring to?

**Comment by mockitoguy** [comment]
>@mockitoguy do you know which problem(s) the comment above is referring to?

Yes. During plain "build" we don't construct the pom file at all. This means that if there is a bug in the release automation that manipulates the pom, we will not find out early enough. Also, Mockito library needs to release to maven local because we have integration tests based on mockito jar + pom from maven local. In the past, we have shipped a version of Mockito with zero dependencies in pom, due to a bug in "build.gradle". Running an integration test against locally released mockito ensures that the pom + jar work ok.

I like the idea of removing line 66 as you suggest. Problem is that it will not help Mockito project. Let's try to find a different solution.

>It looks like the chicken-and-egg problem no longer exists since ComparePublicationsPlugin is not longer using the pom. Therefore we could hit github only if a release is needed now, isn't it?

Well spotted! How about we make it so that during normal build “pom.xml” will not have contributors, but in the release build it will have contributors. It is not ideal but simple enough and solves the problem. I will update the description of the ticket.

**Comment by mockitoguy** [comment]
Hey @epeee, I put my thoughts about the design to the ticket description - any comments / thoughts?

**Comment by epeee** [comment]
@mockitoguy your new idea looks good, thx a lot!

**Comment by mockitoguy** [comment]
Great! Looking forward to reviewing a PR :)

**Comment by mockitoguy** [comment]
Hey @epeee, I'll take a stab at this today. Let me know if you need help with #679
