### ISSUE TITLE
Introduce [ci force-release] commit message keyword

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#353]
### Problem

Currently there is no way to force the release other than making whitespace in Javadoc. Sometimes we need to force the release. For example, I want to ship 2.9.0 version of Mockito despite that the only thing I have changed in the pull request was the version number. The version number is ignored when 'assertReleaseNeeded' task decides if the release is needed.

### Suggested solution

- Update ReleaseNeededTask so that it checks for presence of "[ci force-release]" keyword in the commit message. If the keyword is present, we make the release regardless of other conditions.
- See how currently we inspect commit message for "[ci skip-release]" keyword: [source code](https://github.com/mockito/shipkit/blob/master/src/main/groovy/org/shipkit/internal/gradle/release/tasks/ReleaseNeeded.java#L28).
- Update unit tests for release needed logic
- Be thorough and diligent. We had bugs in release needed logic multiple times because of conditional complexity and difficulties in testing. The impact can be high, unwanted versions published to Central.

Let us know if you want to work on this or if you have any questions!

**Comment by TimvdLippe** [comment]
We were trying to publish a new minor version of Mockito today and this issue is very tedious to work around. Would like to see this fixed soon to prevent needless builds + commits + trying to publish a version
