### ISSUE TITLE
Improve Gradle plugin validation

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#356]
### Problem

Running ```./gradlew validatePlugins``` yields many false positives:

```
> no properties file found for plugin(s):
        'ShipkitJava' (/Users/sfaber/mockito/release/src/main/groovy/org/shipkit/internal/gradle/java/ShipkitJavaPlugin.java)
        'ShipkitConfiguration' (/Users/sfaber/mockito/release/src/main/groovy/org/shipkit/internal/gradle/configuration/ShipkitConfigurationPlugin.java)
        'ShipkitBintray' (/Users/sfaber/mockito/release/src/main/groovy/org/shipkit/internal/gradle/bintray/ShipkitBintrayPlugin.java)        
```

- some plugins have slightly different naming convention, with optional 'Shipkit' prefix
- some plugins don't have plugin id intentionally

### Suggested approach

How about we change the implementation into something like this. Given example resource files:

```
implementation-class=org.shipkit.internal.gradle.java.GitHubPomContributorsPlugin
implementation-class=org.shipkit.internal.gradle.java.ShipkitJavaPlugin
```

For every resource file we: 

1. Ensure naming convention:
	a. convert plugin id to acceptable names, examples
		- "org.shipkit.bintray" -> "OrgShipkitBintrayPlugin", "ShipkitBintrayPlugin", "BintrayPlugin"
		- "org.shipkit.git-hub-pom-contributors" -> "OrgShipkitGitHubPomContributors", "ShipkitGitHubPomContributors", "GitHubPomContributors"
	b. implementation-class must match one of the acceptable names for given plugin id
        c. I would ignore case for simplicity
2. Validate if the implementation class exists
	org.shipkit.internal.gradle.java.GitHubPomContributorsPlugin -> file org/shipkit/internal/gradle/java/GitHubPomContributorsPlugin.java|groovy exists

**Comment by szczepiq** [comment]
@epeee, how does it sound?

**Comment by epeee** [comment]
@szczepiq sounds good, thx!
