### ISSUE TITLE
Shipkit bootstrap does not show the url to release notes

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#364]
## Problem

Output from shipkit bootstrap:

```
  Release shipped!
    - Files in Bintray:   https://dl.bintray.com/shipkit-bootstrap/bootstrap/org/shipkit/bootstrap/sfaber/shipkit-bootstrap/0.0.2
    - Bintray repository: https://bintray.com/shipkit-bootstrap/bootstrap/maven/0.0.2
    - Release notes:      TODO
```

Note the **TODO** for release notes ;)

## Steps to reproduce

Follow the bootstrap steps: https://github.com/mockito/shipkit-bootstrap/wiki/Shipkit-Test-Drive-in-4-steps

**Comment by epeee** [comment]
@szczepiq it looks like we are doing the logging in `performRelease.doLast` specified in shipkit-boostrap (shipkit.gradle). 
see https://github.com/mockito/shipkit-bootstrap/blame/master/gradle/shipkit.gradle#L24-L30

Do you think we should integrate this logging messages into shipkit? Or just fix it in shipkit-bootstrap project?

**Comment by szczepiq** [comment]
Short term, I think we are better off fixing it in bootstrap. This might
involve adding some property that exposes the url.

Long term, it would be great to show at the very end of the build all the
useful links to the outcomes of the release.

Thank you for looking into this!
-- 
Szczepan Faber
Founder @ http://mockito.org | Twitter @ https://twitter.com/mockitoguy
Author @ https://www.linkedin.com/in/szczepiq/recent-activity/posts/

**Comment by szczepiq** [comment]
Let's track in #450
