### ISSUE TITLE
Package parameters for maven deployment

### ISSUE THREAD

**Issue by ashdavies** [mockito/shipkit#374]
I've been looking over what documentation is available, and the project seems really cool, but the descriptions are mostly about the why instead of the "how", this is understandable as I interpret this as a relatively new project.

I'd love to contribute to the documentation, but I'm really not sure about how to use this with a project that I'd like to publish snapshots to maven central with a GPG signed artifact. This might, however, be a very particular use case.

When using this plugin, how might one define the intended artifactory, and/or snapshot repository, as one might with the `uploadArchives` enclosure? Or should this plugin be treated as a compliment to the traditional `maven-publish` plugin?

**Comment by szczepiq** [comment]
Welcome! You are spot on that the project is relatively new and 'how' documentation is missing. Is your current project Open Source so that we can take a look?

Currently, our plugins and tasks are geared for using Bintray. I thought that we have a ticket open to create better integration with Artifactory or Maven Central directly but I couldn't find it.

**Comment by ashdavies** [comment]
Thanks! I've been looking at building a release plugin that does what I need for my open source projects (particularly [this one](https://github.com/ashdavies/auto)), but this project seemed pretty interesting so I thought I'd give it a try.

I noticed the `JavaPublishPlugin` so I figured the support is there, just not so well documented yet 😉 

I'm assuming the configuration would be something similar to how it is done [here](https://github.com/mockito/mockito/blob/release/2.x/gradle/shipkit.gradle), but I'm not sure how it would need to differ for Maven distribution.

**Comment by szczepiq** [comment]
Hey @ashdavies, we can work together and have Shipkit set up for your project. We would document what's needed on the way.

We don't support publishing snapshot artifacts to maven central out of the box. This needs to be implemented first :) Why not publishing every version to a Bintray and only some versions to Maven Central? Wouldn't that satisfy the 'snapshot' version use case?

**Comment by ashdavies** [comment]
I think I'll start with this and then try to see where I can improve along the way, thanks for the help!
