### ISSUE TITLE
Please make it easy to start using it

### ISSUE THREAD

**Issue by smougenot** [mockito/shipkit#408]
After an hour of tries and errors, I'm forced to abandon the idea of using this tool.
I'm very sad.

Problems :
* Could not find a proper entry point for documentation (there are some .md, some docs/*.md, some wiki page, other are in the mockito project .... very messy)
* Could not find process/sample of how to add this to my project (lot of things need configuration like tools access)
* Had to gather sample code from Mockito to try this (I do not have time to reverse engineering your build)

At the end I'm not more advanced than after the first 5 minutes :
```
>./gradlew updateReleaseNotes
...
GET https://api.github.com/repos/mockito/shipkit/contributors?access_token=e7fe8fcfd6ffedac384c8c4c71b2a48e646ed1ab&per_page=100
:fetchContributors FAILED
```

Looks like even authentication tokens are embedded into the gradle plugin. 😨

**Comment by StefMa** [comment]
I see your frustration.
I already watch that project quite a while and hope that something changes with the documentation.
Unfortunately there haven't changed something yet.

But instead of "bulling" feel free to contribute 👍 
There is already a [blog post](https://up.smartrecruiters.com/shipkit-getting-started-39c55782fa7)  and (as you mentioned) some docs (in the wiki, some in the docs/ etc.)

I think it is a good idea to start a discussion with @epeee (and or @szczepiq ) to define where we should place the documentation...?

Btw. there is already another issue #362.

**Comment by smougenot** [comment]
Sorry,
Maybe my wording was hard but I didn't intended to be bully.
I was all the more disappointed that the very purpose (according to the doc) is seamless easy efficient release.

My opinion is this project deserve more easy access. And I wanted to get some attention on that.

For contributing, I do try to contribute. But I won't reverse engineer the required settings of that opaque project. It's far too risky. And some people from the project should be able to craft a blank project in minutes with actual tips & tricks mentioned.

But I'd be glad to beta test any documentation/process on my projects if it can help.

**Comment by szczepiq** [comment]
This is really good feedback, thank you!

I almost finished creating bootstrap project: https://github.com/mockito/shipkit-bootstrap/wiki

I promise to have the docs ready by the end of the week!

**Comment by wwilk** [comment]
Hi @smougenot, I created a getting started wiki page. You can find it here:
https://github.com/mockito/shipkit/wiki/Getting-started-with-Shipkit
It should be enough to start using Shipkit, if there is any other problem with it please let me know. I would be happy to help. 

The token you mentioned is configurable. This is only the default value, which is set for implementation reasons. You can easily change it in shipkit.gradle config file. It is all explained in getting started guide.

Thanks for this post, documentation is our weakest spot at the moment and we have to address these issues.

**Comment by smougenot** [comment]
Looks fine, I can't give it a try now but i gives me clues about what to do.
Hope it will be easier to integrate using that
Thank you

**Comment by szczepiq** [comment]
I updated the getting started guide just now. It looks pretty good! Thank you very much @wwilk!
