### ISSUE TITLE
subprojects dir is weird

### ISSUE THREAD

**Issue by StefMa** [mockito/shipkit#409]
Hey guys,

the current project "skeleton" is really weird.
Especially for new - or potential new - contributors.

Why live the [ShipKit code](https://github.com/mockito/shipkit/tree/master/subprojects/shipkit) - the ❤️  of that project - in a directory called "subprojects".
And what is the [testDownstream](https://github.com/mockito/shipkit/tree/master/subprojects/testDownstream) project (which includes just one gradle file)? 😕

I think ~people~ contributors - or is it just me? 🤔 - expect a dir called `src` or `shipkit` which contains only the source code for the real ShipKit project...

**Comment by szczepiq** [comment]
Hey!

Sorry we didn't reply earlier. Subprojects just makes more sense :) It is weird that some source code is in "src" and some source code is under "subproject/src". It makes the top level directory cleaner.

Please suggest changes to our documentation if you think it is useful!

**Comment by szczepiq** [comment]
I will close it if that's ok ;)
