### ISSUE TITLE
Update gradle

### ISSUE THREAD

**Issue by StefMa** [mockito/shipkit#410]
Gradle is still on version `2.14.1`. [See here](https://github.com/mockito/shipkit/blob/master/gradle/wrapper/gradle-wrapper.properties#L6).

This needs to be updated..

Are there currently any reason to don't do so?
Gradle is currently on [4.1 ](https://github.com/gradle/gradle/releases)🙃

**Comment by szczepiq** [comment]
The reason we are on lower version of Gradle is because we don't want to block potential users who still use old version of Gradle.

Let's release Shipkit with Gradle 2 compatibility and then discussion whether to move the baseline version. For now, I'll close the ticket.

**Comment by StefMa** [comment]
Hmm.. the gradle version of the project have nothing todo with the gradle version from users, right? 🤔 

The only thing is that we *can compile* with gradle 2. We use all gradle 2 APIs in shipkit.
Which means if we use gradle 4 we can compile/build/use all APIS from gradle 4.
But that doesn't mean that users have to use at least gradle version 4.. or am I wrong? 🤔

**Comment by szpak** [comment]
@StefMa You are not. There is a risk to have some glitches (especially for plugins written in Groovy - Shipkit is in Java), however, I created regression tests to confirm that it (at least basic scenarios) works fine. Nevertheless, it wasn't thoroughly tested and I understand that Szpepan is careful about that.

On the other hand, @szczepiq wouldn't it be a breaking change (according to your definition) to switch Gradle from 2.x to 4.x once Shipkit 1.x is released? In that case people would need to wait for Shipkit 2.x to have some features of Gradle 3/4 (such as caching awareness) available. That would be sad.
