### ISSUE TITLE
testRelease fails in non configured environment

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#415]
I would be good to have testRelease in shipkit-example up and running to new contributors to test their changes before making a PR. Currently, on a "fresh environment" it fails:

```
gw testRelease
(...)
[releaseNeeded] :gitPush
[releaseNeeded]   'git push' does not use GitHub write token because it was not specified
[releaseNeeded]   Executing:
[releaseNeeded]     git push https://github.com/mockito/shipkit-example.git v0.16.8 master --dry-run
[releaseNeeded] :gitPush FAILED
[releaseNeeded] 
[releaseNeeded] FAILURE: Build failed with an exception.
[releaseNeeded] 
[releaseNeeded] * What went wrong:
[releaseNeeded] Execution failed for task ':gitPush'.
[releaseNeeded] > Execution of command failed (exit code 128):
[releaseNeeded]     git push https://github.com/mockito/shipkit-example.git v0.16.8 master --dry-run
[releaseNeeded]     Captured command output:
[releaseNeeded]   fatal: could not read Username for 'https://github.com': No such device or address
```

Even `-x gitPush` doesn't help as gitPush in a dry-run mode is executed in a Gradle subprocess.

**Comment by szczepiq** [comment]
Taking a look. I might have broken it with my recent changes. Charms of 0.x release :)

**Comment by szczepiq** [comment]
```
fatal: could not read Username for 'https://github.com': No such device or address
```
I haven't investigated the code yet but it seems that shipkit-example is tailored for Shipkit developers and may be failing for "regulare" GitHub users who are not developers with push rights to Shipkit repos.

**Comment by szpak** [comment]
`testRelease` shouldn't do just a test?

**Comment by szpak** [comment]
Especially with https://github.com/mockito/shipkit/issues/416 it is problematic to change your local changes before making a pull request.

**Comment by szczepiq** [comment]
The dilemma is easy to use vs. confidence of a test. To make ```testeRelease``` give high quality signal, we also want to test ```gitPush``` and ```bintrayUpload```. However, those commands need Shipkit Developer permissions. "CONTRIBUTING.md" contains information how to test locally for users.

Do you have suggestions on how to improve it / fix it?

**Comment by szpak** [comment]
From contributing.md:
> Local development
> Test most things, without actually making any code pushes/publications: ./gradlew testRelease -x gitPush -x bintrayUpload

It doesn't work. `-x gitPush -x bintrayUpload` is not propagated to the underlying Gradle process which in turn results in the aforementioned error.

What is a recommenced way to test local changes by external contributors?

**Comment by szczepiq** [comment]
Oups, bug in documentation!

I'd recommend doing exactly what the "./gradlew testRelease" does behind the hood, -x gitPush -x bintrayUpload. Perhaps we need another task "./gradlew contributorTestRelease" plus some message when "./gradlew testRelease" fails, we inform that contributors should use "./gradlew contributorTestRelease".

@szpak, what are your thoughts?

**Comment by szpak** [comment]
I don't know how many external contributors Shipkit has. Nevertheless, it would be good to make that process as simple as possible. Maybe it would be enough to be able to define other remote to push (#416) and information how to define user's own bintray API key (and setup a repo to upload to)? However, the later would be probably problematic for majority of people... Therefore, maybe your idea is the easiest one.
