### ISSUE TITLE
shipkit.gitHub.url set in project config seems to be ignored

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#416]
An output of #415. Tested with shipkit-example. Configuration in `gradle/shipkit.gradle`:
shipkit.gitHub.url = "file:///tmp/shipkit-example"

`gitPush` task still tries to put to remote repo:

```
[releaseNeeded] Execution failed for task ':gitPush'.
[releaseNeeded] > Execution of command failed (exit code 128):
[releaseNeeded]     git push https://github.com/mockito/shipkit-example.git v0.16.8 gradle41 --dry-run
[releaseNeeded]     Captured command output:
[releaseNeeded]   fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by szczepiq** [comment]
Thanks for reporting!

- shipkit.gitHub.url is not the push url but the url of the GitHub API that we talk to when getting issue information, etc. Let us know or suggest a fix if it is not documented well enough.
- currently, we don't have a documented way to push/test to the local repo on filesystem. In theory, one could figure it out and set the url on the GitPush task, etc. However, nobody tested it yet :)
- How important that use case is? I think I will close this ticket. If we want to keep it open, can you describe the use case better? Thanks!
