### ISSUE TITLE
Make publication repository configurable in shipkit file

### ISSUE THREAD

**Issue by StefMa** [mockito/shipkit#427]
### Problem

When using 'org.shipkit.gradle-plugin' the user needs to remember to configure publication repository on the task: https://github.com/mockito/shipkit/blob/master/gradle/shipkit.gradle#L10 We want the shipkit configuration to be central point of the important configuration. Unimportant configuration settings are fine at the task level. Publication repository setting is important because without it we cannot generate release notes for 'org.shipkit.gradle-plugin' users.

### Suggested implementation

See the initial design at #430

**Comment by szczepiq** [comment]
@StefMa, I updated the description and hacked my initial thoughts about the implementation. Do you want to take a stab at it? We love contributions!!! :)

**Comment by StefMa** [comment]
Since #446 is merged. This can be closed.
