### ISSUE TITLE
Documentation for Shipkit 1.0 release

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#432]
Let's sort out the documentation before 1.0 release.

 - [x] - move all documentation from wiki to checked-in markdown files to help with contributions
 - [x] - update history, conference links, meetup links
 - [x] - update README.md
 - [x] - update how-shipkit-works.md
 - [x] - make bootstrap use getting started guide, retire bootstrap wiki

After the release we will continue working on the documentation: #534

**Comment by szczepiq** [comment]
I am going to chip away the TODOs until we are ready

**Comment by wwilk** [comment]
This is related to #362

**Comment by mockitoguy** [comment]
This ticket is done!
