### ISSUE TITLE
upgradeDownstream creates loop of pull requests

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#443]
### Problem

upgrade-downstream plugin is amazing! It would be great if it worked better for this scenario:
1. pull request with nice change opened to shipkit
2. we merge it
3. new version released, upgrade downstream creates "version upgrade" pull request to shipkit
4. we merge "version upgrade" pull request
5. step 3 is now repeated, creating a loop of merge + pull request without any changes.

### Possible solution

I suspect that this will be automatically solved when we fix #419

**Comment by wwilk** [comment]
This one is fixed with build: https://travis-ci.org/mockito/shipkit/builds/297167721
First version not affected by the bug: 0.9.139
