### ISSUE TITLE
Setting contributors explicitly breaks task `updateReleaseNotes`

### ISSUE THREAD

**Issue by myniva** [mockito/shipkit#516]
If the contributors are set explicitly in the ShipKit configuration, the `updateReleaseNotes` task fails with this exception:

    A problem was found with the configuration of task ':updateReleaseNotes'.
    > File '.../build/shipkit/all-contributors.json' specified for property 'contributorsDataFile' does not exist.

See https://github.com/myniva/gradle-s3-build-cache/commit/73789368015a91c003c242967889102f012795d7 and https://travis-ci.org/myniva/gradle-s3-build-cache/builds/289614934 for example.

**Comment by wwilk** [comment]
@myniva Thanks for reporting it! I'll investigate :)
