### ISSUE TITLE
fetchContributors always run, even when not releasing

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/shipkit#566]
The task `fetchContributors` is always run, even when I am not calling `performRelease`. This happens when I execute `./gradlew clean test` or `./gradlew clean build` for example. Would be great if this task is not executed if I am not invoking any release task.

Originally filed at https://github.com/mockito/mockito/issues/1248

**Comment by epeee** [comment]
Thx for reporting this one.
It seems to be related to #345.

**Comment by mockitoguy** [comment]
Closing as duplicate of #345. @TimvdLippe, thank you for reporting!!! @epeee, do you want to take a stab at #345?
