### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by mstachniuk** [mockito/shipkit#61]
### Problem

Currently mockito-release-tools works only with github.com. A path to it is hardcoded in the code :(. This project needs to works with [GitHub Enterprise API](https://developer.github.com/v3/enterprise/) otherwise it cannot be used in enterprise setting. A property to configure GitHub Enterprise needs to optional and by default it should works with github.com.

### Suggested implementation

ReleaseConfiguration.GitHub should have an optional setting for the url base host:

```Gradle
releasing {
    github.apiUrl = "https://github.in.your.company.com/api/v3"
    github.url = "https://github.in.your.company.com"
}
```

- [ReleaseConfiguration.GitHub](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/gradle/ReleaseConfiguration.java#L148) class that needs new properties.
- Example of [hardcoded GitHub API url](https://github.com/mockito/mockito-release-tools/blob/master/src/main/groovy/org/mockito/release/notes/improvements/GitHubTicketFetcher.java#L153), there are other places but this one is a good starting point.

**Comment by szczepiq** [comment]
@mstachniuk, can you confirm suggested implementation above?

**Comment by mstachniuk** [comment]
I suggest to add 2 options to the configuration:
```
releasing {
    github.api = "https://github.in.your.company.com/api/v3"
    github.url = "https://github.in.your.company.com"
    // others ...
}
```

The first one to the API endpoint for generation API requests and second one for generating links for  developers in pom (see: PomCustomizer.groovy)

**Comment by szczepiq** [comment]
Nice proposal! I updated "api" -> "apiUrl". Let's make sure they are defaulted so that we don't have to configure it for typical OS builds.
