### ISSUE TITLE
Empty Dependency Info files generated causing missed releases

### ISSUE THREAD

**Issue by magneticflux-** [mockito/shipkit#619]
Example Travis CI build where dependencies changed but no new release: [Link](https://travis-ci.org/magneticflux-/kotlin-simplexml-rss/builds/330097438)

I inspected the module-dependencies.md files in my releases back to at least `1.0.2` of my project and they're all empty, so this seems like it's been around for a while. I never noticed an issue before though because I changed the sources as well.

EDIT:
I believe it is due to this line: [link](https://github.com/mockito/shipkit/blob/master/subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/java/tasks/CreateDependencyInfoFile.java#L29). I'm not sure, but it may be because my project is a top-level project so Shipkit and my dependencies are declared at the same level. Perhaps that line ignores dependencies of the top-level project, instead only getting dependencies from subprojects/modules?

**Comment by wwilk** [comment]
Hey @magneticflux- thank you for reporting the issue! I will investigate

**Comment by epeee** [comment]
I just had a look at this one. It looks like we are generating empty dependency info files if the `java-library` plugin is used.
I already have an idea how to solve this one.

**Comment by epeee** [comment]
@magneticflux- thx for reporting this one! This problem is fixed in Shipkit v2.0.7.
