### ISSUE TITLE
Information about Shipkit in release notes file

### ISSUE THREAD

**Issue by mstachniuk** [mockito/shipkit#62]
### Introduction

The success of the project depends on popularity. We want to gamify continuous delivery, promote frequent releases and release automation goodness. Let's use [real estate available in the release notes](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md) file to promote the project and get more folks aware of what we're doing and why. 

### Suggested implementation

During updating release notes file we can add (or modify if exist) this sentence on the top of release note file:

_This release notes was automatically generated by [shipkit](http://shipkit.org) X times._

Where X start from 1 and it's incremented by each new released version. This sentence should be formatted as small if possible.

We can make this potentially configurable. Parsing and loading the release notes file should not be difficult.

### Code

- this is [how we update release notes](https://github.com/mockito/mockito-release-tools/blob/083457a5801ea95b0385df0dc6e2d3c4e4e4f8a8/src/main/groovy/org/mockito/release/gradle/IncrementalReleaseNotes.java#L175) file
- and that's how we [create release notes content](https://github.com/mockito/mockito-release-tools/blob/083457a5801ea95b0385df0dc6e2d3c4e4e4f8a8/src/main/groovy/org/mockito/release/gradle/IncrementalReleaseNotes.java#L154) for new version

Looking forward to reviewing your pull request! :)

**Comment by szczepiq** [comment]
Really cool idea. I like the gamification part of it :)

**Comment by anicos** [comment]
Hi. I would like to contribute. Can you assign this task to me?
@mstachniuk I have question about X value. What does it mean incremented by each generation? Every invocation of updateReleaseNotes in gradle? or every new version of release note file for example every commit increment or merge increment the counter?

**Comment by mstachniuk** [comment]
Hi @anicos You can take this task, but we can't assign you because you are not a core team member. But we will remember about you :-)
Regarding `X` value: By default each successful build on Travis-CI:
* generate release notes
* create git tag
* commit this changes to master

Of course shipkit make more other things, but this are important in scope of this ticket. If this line doesn't exist in release notes file you need to assign `X = 1`. If it exists, you have to increment X. This should happens in `updateReleaseNotes` task. By testing this task locally, if you call `updateReleaseNotes` twice, `X` should be also incremented x2. It's not a problem so long you don't commit it ;-)

I hope it's more clear now, if not please ask me ;-)

**Comment by anicos** [comment]
@mstachniuk thanks for answer. I see that are two implementation of formatter [DetailedFormatter](https://github.com/mockito/shipkit/blob/master/src/main/groovy/org/shipkit/internal/notes/format/DetailedFormatter.java) and [NotableFormatter] (https://github.com/mockito/shipkit/blob/master/src/main/groovy/org/shipkit/internal/notes/format/NotableFormatter.java) but NotableFormatter is unused. Where I should put  this functionality?  Only in DetailedFormatter? Do you have any chat? Conversation on github is not the fastest way to communication :)

**Comment by wwilk** [comment]
Probably it would be enough to add it to DetailedFormatted, as you said NotableFormatter is not used. 

I'll add @szczepiq to the conversation because he was the one who gave up on notable notes so he knows best the reason for keeping NotableFormatter. 

We have a slack account and google email group but it is good to keep this kind of discussion here, I think.

**Comment by mstachniuk** [comment]
@anicos I send you an invitation to chat via Google Hangout. You can implement that only in `DetailedFormatted`. `NotableFormatter` is no longer supported, it's now a dead code, but it can happen that we come back to this concept after 1.0 version.

**Comment by anicos** [comment]
Regarding to `X` value. Adding it is not easy for the following reasons:

- Release notes file were not designed to read data from these file. The logic of update would be very complex if we want to add this functionality.

- We have two scenarios:

     > First: If there is no sentence with the number `X` so we add it to the top of the release note. This case is simple.

    > Second: If there is the sentence, we need to do the following.
    > Read the release note file and check is there is the sentence. Then we read the last `X` and get it
    > Then we have to remove the old sentence from previous release note
    > Then we add have add new content with a new sentence that has an incremented by 1 value `X`

Right now logic of update it is very simple we append new content on top off file. But after these changes   logic will be quite complicated, and if the structure of release note file changes, we will need to remember about migration to keep the continuity of the numbering. Because suggested implementation is reading release note file. 

I have other solution. What would you say to the proposal that the number `X` was calculated on the `number of git commit + 1`?. That way don't have to read the release note file.

**Comment by mstachniuk** [comment]
@anicos `number of git commit` is not an option. 

Second scenario described by you is a little bit complicated but not impossible. Remember that the sentence should be only once in release notes and always on top. And the sentence text is constant!

If there is the sentence:
* You read the whole file
* Read `X` from sentence
* Store the rest of release notes (without sentence) in temporary value `TMP`
* Concatenate: Sentence(with X+1) + newest release notes (the newest part - this is current logic) + `TMP`
* Store it in release notes file

I hope it's not so hard :-)  Try to do PullRequest and we will help you by commenting the code.

**Comment by anicos** [comment]
@szczepiq can we talk about this issue on chat? Because I have some questions related to this task. I put these question in pull request.

**Comment by szczepiq** [comment]
I believe this is completed. Thank you guys!
