### ISSUE TITLE
Upgrade to Java8 and Gradle4

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#624]
How about we upgrade to Java8 and Gradle4?

We can produce Shipkit 2.0 that would have only one incompatible change: Java8 + Gradle4. For uses on lower versions of those, they can use Shipkit 1.0 (compatible feature-wise, public API wise). For users that want latest improvements, they need to be on Java8 + Gradle4. This is the best of both worlds - we still have a working version for old Java and Gradle but we are not blocked using latest features of Java (very needed, see the bug #621)

Thoughts?

**Comment by epeee** [comment]
+1, yep, let's go for Shipkit 2.0 and do the upgrades.
