### ISSUE TITLE
mergePullRequest is not merging the pr due to 'No checks defined in pull request'

### ISSUE THREAD

**Issue by epeee** [mockito/shipkit#634]
After solving #629 we are still not able to automatically merge pr's. 

> [upgradeDownstream] [performVersionUpgrade] :mergePullRequest
> [upgradeDownstream] [performVersionUpgrade]   [INCUBATING] merge pull requests is incubating and may change in any version.
> [upgradeDownstream] [performVersionUpgrade] Waiting for status of a pull request in repository 'mockito/shipkit' between base = 'master' and head = 'mockito:upgrade-shipkit-to-1.0.12'.
> [upgradeDownstream] [performVersionUpgrade] No checks defined in pull request https://api.github.com/repos/mockito/shipkit/pulls/633! Merge aborted.

see [travis build log](https://travis-ci.org/mockito/shipkit/builds/342197410#L1116) for details.

**Comment by mockitoguy** [comment]
Thank you for reporting! Do you want to take a stab at it?

**Comment by epeee** [comment]
yep, I will have a look at this one.

**Comment by epeee** [comment]
Doing one retry does the trick, let's close this one.
There is still one problem remaining until we are able to automatically merge pr's. I will create a new issue.
