### ISSUE TITLE
Publication(s) comparison doesn't handle dependency change only

### ISSUE THREAD

**Issue by szpak** [mockito/shipkit#679]
One commit in Mockito changed only the project [dependencies](https://github.com/mockito/mockito/commit/cbc7a99db706621bdb6728cb64d2b0d9be6a8034). The corresponding Shipkit Travis [build](https://travis-ci.org/mockito/mockito/jobs/357999739#L983) detected no changes in publications and the release hasn't been executed.

As a workaround the release has to forced manually.

**Comment by epeee** [comment]
Thx for reporting this one!
I will have a look at it.

**Comment by epeee** [comment]
It looks like this one is already fixed in a newer version of shipkit (might be fixed by #619).
I'm currently doing some local testing using a newer shipkit version and will provide a pr for updating shipkit in mockito project soon.

**Comment by szpak** [comment]
Thanks @epeee for taking care of that so quickly!

**Comment by epeee** [comment]
does work in shipkit 2.0.12, see
```
> Task :releaseNeeded 
  Commit message to inspect for keywords '[ci skip-release]' and '[ci skip-compare-publications]': <unknown commit message>
  Current branch 'release/2.x' matches 'release/.+': true

  Compared 4 publication(s). Changes since previous release:
  Differences between files:
  --- /home/ep/tmp/mockito/subprojects/junit-jupiter/build/previous-release-artifacts/junit-jupiter-2.17.0-sources.jar/META-INF/dependency-info.md
  +++ /home/ep/tmp/mockito/subprojects/junit-jupiter/build/libs/mockito-junit-jupiter-2.17.1-sources.jar/META-INF/dependency-info.md

    Here you can see the changes in declared runtime dependencies between versions.

    @@ -5,0 +5,1 @@
    + - org.junit.jupiter:junit-jupiter-engine:5.1.0

```

**Comment by epeee** [comment]
closing this one since mockito is using Shipkit v2.0.13 now.
