### ISSUE TITLE
Using Gradle 4.8[.1] leads to errors

### ISSUE THREAD

**Issue by sormuras** [mockito/shipkit#727]
### Using Gradle 4.8[.1] produces `value: ` strings

See this log excerpt:

```
[performRelease] > Could not upload to ‘https://api.bintray.com/content/[secure]/maven/[secure]-bartholdy/0.0.1/value:
de/[secure]/bartholdy/value: [secure]-bartholdy/value: 0.0.1/value: [secure]-bartholdy-value: 0.0.1.pom’:

HTTP/1.1 400 Bad Request [message:Unable to upload files:
Maven group, artifact or version defined in the pom file do not match the file path
‘value: de/[secure]/bartholdy/value: [secure]-bartholdy/value: 0.0.1/value: [secure]-bartholdy-value: 0.0.1.pom’]
```

Log: https://travis-ci.com/sormuras/bartholdy/jobs/131336882#L824

### Using Gradle 4.7 works

After downgrading to Gradle 4.7, everything works as expected.

https://travis-ci.com/sormuras/bartholdy/builds/77327312

### Potential underlying reason

@marcphilipp pointed out that there was change in _internal_ `AbstractProvider` class:

https://github.com/gradle/gradle/blob/v4.8.1/subprojects/core/src/main/java/org/gradle/api/internal/provider/AbstractProvider.java#L57

Related commit: https://github.com/gradle/gradle/commit/5884d648d6a7b07f439e254c44a42057402374b8#diff-21e080372a1e92287c45bfa78b444a16

Does Shipkit use this internal type? Or `MavenProjectIdentity`?

**Comment by epeee** [comment]
Thank you for reporting this one.
We are using gradle bintray plugin for publishing and it looks like the problem should already be fixed in a new version of the bintray plugin, see https://github.com/bintray/gradle-bintray-plugin/issues/234.
I will adjust our plugin and provide a pr.
