### ISSUE TITLE
Automatically update releases on GitHub

### ISSUE THREAD

**Issue by TimvdLippe** [mockito/shipkit#75]
GitHub has nice releases (https://github.com/mockito/mockito/releases), but we are not using them right now. It would be great if the changelog can be published there. The corresponding endpoint is https://developer.github.com/v3/repos/releases/#create-a-release

It would also be nice if "notable versions" would be released as a full release, while all other versions are released as pre-release (see the boolean parameter to the endpoint).

**Comment by szpak** [comment]
I've been using [Chandler](https://github.com/mattbrictson/chandler) for a CHANGELOG.md file synchronization and it works fine (maybe except for https://github.com/mattbrictson/chandler/issues/33). Alternatively the mentioned API can be used directly to do not use a Ruby application.

**Comment by szczepiq** [comment]
Great idea! Thank you for submitting!!!

**Comment by thekingnothing** [comment]
I'm voting for the feature.

**Comment by jpkrohling** [comment]
We could make use of this for the Jaeger project as well. This is probably the only manual step remaining for our release process.

**Comment by TimvdLippe** [comment]
This was implemented in #766
