### ISSUE TITLE
Option to skip changelog

### ISSUE THREAD

**Issue by jpkrohling** [mockito/shipkit#753]
For the cases where the changelog is generated somewhere external to Shipkit, it would be useful to have an option to disable this part of Shipkit.

The workaround I can think of is to keep it "hidden", like at `.shipkit/changelog.md`

**Comment by mstachniuk** [comment]
You can skip execution of `updateReleaseNotes` task:

Solution 1 - Command line
`./gradlew ciPerformRelease -x updateReleaseNotes`

Solution 2 - in Gradle script:
`updateReleaseNotes.enabled = false`

https://android.jlelse.eu/skip-several-tasks-in-gradle-quickly-dcd0a11c3487

**Comment by jpkrohling** [comment]
Awesome, thanks!

**Comment by mstachniuk** [comment]
Btw. @jpkrohling What do you use for generation changelog and why not mechanism provided by Shipkit?

**Comment by jpkrohling** [comment]
We do that manually, but if we were given an option to have the changelog follow our template, we would possibly use it (see #194)
