### ISSUE TITLE
Question: Using shipkit in part with maven-publish

### ISSUE THREAD

**Issue by jjstreet** [mockito/shipkit#768]
I am successfully using shipkit to manage my versions and for adding releases in github. I am not using the publishing parts because I don't release publicly to bintray or maven central. I instead am trying to use the standard maven-publish plugin gradle provides.

The maven-publish plugin will read from version.properties, and because the version is bumped by shipkit, it publishes the artifacts at the next version as anticipated by shipkit, not the "previous" which is the latest released.

How can I get these plugins to play nicely? Or can I get shipkit to handle publishing by using the maven-publish plugin somehow?

**Comment by jjstreet** [comment]
As a workaround I've set the version of the artifacts to publish to the previous version as specified in the `VersionInfo` object thats in the root project:
```groovy
publications {
  somewhere(MavenPublication) {
    version rootProject['org.shipkit.version.VersionInfo'].previousVersion
    from components.java
  }
  ...
}
```

Its kludgy because my jenkins pipeline says I'm building one version for `clean build` and the git tasks. Then executing it again, it says its building the next version because of the version bump.

I might be running right into a design limitation because shipkit expects tasks to be chained together in one execution. Breaking them up doesn't work too well, at least as evidenced by me here.

**Comment by jjstreet** [comment]
I'm trying to harness shipkit for an "inner-source" (new term i learned today) project. Meaning, its not intended for release publicly. Therefore, it will never be released into MavenCentral, and will not be published to bintray.

**Comment by mstachniuk** [comment]
Ok, so do you would use maven-publish to publish to internal
nexus/artifactory? Maybe bintray plugin will be able to publish to the
intern repository?

śr., 16 sty 2019, 23:52: Joshua Street <notifications@github.com>
napisał(a):

**Comment by jjstreet** [comment]
Perhaps. I will look into that. It would be nice if shipkit abstracted the way it used bintray to allow a transparent passthrough to the maven-publish plugin for users that cannot publish to bintray first.

**Comment by epeee** [comment]
Hi,
I'm also using shipkit and maven-publish plugin to publish artifacts internally.
I will be able to provide more details tomorrow.

**Comment by mstachniuk** [comment]
@epeee Please add it to documentation (and review https://github.com/mockito/shipkit/pull/750 please)

**Comment by eximius313** [comment]
@epeee any news on this?

**Comment by mstachniuk** [comment]
@epeee Any news about documentation how to use Shipkit with maven-publish?
