### ISSUE TITLE
Github release notes encoding

### ISSUE THREAD

**Issue by krzemin** [mockito/shipkit#813]
During Shipkit workshops with @mstachniuk we discovered that there is wrong encoding in github release notes published by shipkit: https://github.com/krzemin/shipkit-workshop-15/releases/tag/v1.0.1, while `docs/release-notes.md` file encoding is fine https://github.com/krzemin/shipkit-workshop-15/blob/master/docs/release-notes.md

Is it shipkit to blame?

**Comment by koyemanaung** [comment]
supporting

**Comment by DrAryone** [comment]
supporting up my account protect fix feature.
