### ISSUE TITLE
Disabling Release Notes Generation

### ISSUE THREAD

**Issue by lpellegr** [mockito/shipkit#833]
Is there a way to disable release notes generation with the Gradle plugin? we are already managing a changelog manually following the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

**Comment by mstachniuk** [comment]
Sure, it is. Please add in your build.gradle file:
```
updateReleaseNotes.enabled = false
updateReleaseNotesOnGitHub.enabled = false
```

This is a standard Gradle mechanism for disabling tasks.

Thanks a lot for a link to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/). Do you generate your release notes automatically? What do you use for that?

**Comment by lpellegr** [comment]
Thanks for your answer. 

Currently, the changelog is maintained quite manually.

I have added the provided configuration in my build.gradle. Unfortunately, upon releasing a failure happens because the `gitCommit` task tries to add docs/release-notes.md to the commit, whereas the file does not exists :X

**Comment by lpellegr** [comment]
Creating an empty file and adding it to versioning fixes the issue but it implies to track it with git.
