### ISSUE TITLE
github access_token query parameter deprecated, breaks after 2020/07/01

### ISSUE THREAD

**Issue by nallar** [mockito/shipkit#864]
deprecation notice should be here but it's 404ing: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

**Comment by mockitoguy** [comment]
Thanks for reporting!

**Comment by magneticflux-** [comment]
Here's a newer post on the issue: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

**Comment by mockitoguy** [comment]
@shestee, can you take a look at this issue?

**Comment by shestee** [comment]
@mockitoguy Sure, I'll check this out.

**Comment by magneticflux-** [comment]
@nallar Closed by #871 now?

**Comment by nallar** [comment]
Thanks! ^_^
